config_version = 2

[bar.default]
capsule = true
end = [ "media", "tray", "notifications", "network", "bluetooth", "volume", "brightness", "control-center", "session" ]
margin_ends = 10
scale = 1.1500000096857548
start = [ "launcher", "workspaces" ]
thickness = 40

[brightness]
enable_ddcutil = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-2",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004"
]

    [lockscreen_widgets.grid]
    cell_size = 32
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1317.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 1357.5
    cy = 382.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "clock"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1132.0
    cy = 382.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "weather"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 720.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "sysmon"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 0.0
    box_width = 0.0
    cx = 755.0
    cy = 409.5
    output = "HDMI-A-2"
    rotation = 0.0
    type = "media_player"

[nightlight]
enabled = true

[osd]
position = "top_right"

[shell.panel]
launcher_categories = false

[[shell.session.actions]]
action = "lock"
countdown_seconds = 5.0
enabled = true
shortcut = "1"
variant = "default"

[[shell.session.actions]]
action = "logout"
countdown_seconds = 5.0
enabled = true
shortcut = "2"
variant = "default"

[[shell.session.actions]]
action = "lock_and_suspend"
countdown_seconds = 0.0
enabled = true
shortcut = "3"
variant = "default"

[[shell.session.actions]]
action = "reboot"
countdown_seconds = 5.0
enabled = true
shortcut = "4"
variant = "default"

[[shell.session.actions]]
action = "shutdown"
countdown_seconds = 5.0
enabled = true
shortcut = "5"
variant = "destructive"

[theme]
builtin = "Kanagawa"
mode = "dark"

[wallpaper]
directory = "~/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/zekus/Pictures/Wallpapers/w11black.jpg"

    [wallpaper.last]
    path = "/home/zekus/Pictures/Wallpapers/w11black.jpg"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/zekus/Pictures/Wallpapers/w11black.jpg"

[widget.launcher]
glyph = "apps"

[widget.workspaces]
display = "none"
max_label_chars = 2