[bar.default]
end = [ "media", "tray", "notifications", "network", "bluetooth", "volume", "brightness", "control-center", "session" ]
margin_ends = 10
start = [ "launcher", "workspaces" ]
thickness = 40

[brightness]
enable_ddcutil = true

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-2"]
    box_height = 0.0
    box_width = 0.0
    cx = 1280.0
    cy = 1317.0
    output = "HDMI-A-2"
    rotation = 0.0
    type = "login_box"

[nightlight]
enabled = true

[osd]
position = "top_right"

[shell.panel]
launcher_categories = false

[theme]
builtin = "Kanagawa"

[wallpaper]
directory = "~/Pictures/Wallpapers"

    [wallpaper.default]
    path = "/home/zekus/Pictures/Wallpapers/wallhaven-oggvw9.jpg"

    [wallpaper.last]
    path = "/home/zekus/Pictures/Wallpapers/wallhaven-oggvw9.jpg"

    [wallpaper.monitors.HDMI-A-2]
    path = "/home/zekus/Pictures/Wallpapers/wallhaven-oggvw9.jpg"

[widget.launcher]
glyph = "apps"
scale = 1.25

[widget.workspaces]
display = "none"
max_label_chars = 2
scale = 1.25