[package]
disabled = true

[cmd_duration]
disabled = true

[git_branch]
style = "bold cyan"

[aws]
disabled = true

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
disabled = true

[docker_context]
disabled = true
