[package]
disabled = true

[golang]
symbol = "G:"

[java]
symbol = "J:"

[nodejs]
symbol = "N:"

[python]
symbol = "P:"

[ruby]
symbol = "R:"

[rust]
symbol = "RS:"

[cmd_duration]
disabled = true

[git_branch]
style = "bold cyan"

[aws]
disabled = true
symbol = "A:"

[elixir]
symbol = "Ex:"

[erlang]
symbol = "Er:"

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
disabled = true
