{
  neobones = {
    "type" = {fg = "#6E99B2";};
    "type.builtin" = {fg = "#6E99B2";};
    "type.enum.variant" = {fg = "#A7B3AE"; modifiers = ["bold"];};
    constructor = {fg = "#9AA6A1"; modifiers = ["bold"];};
    constant = {fg = "#939E99"; modifiers = ["italic"];};
    "constant.builtin" = {fg = "#939E99"; modifiers = ["italic"];};
    "constant.builtin.boolean" = {fg = "#C6D5CF"; modifiers = ["italic"];};
    "constant.character" = {fg = "#939E99"; modifiers = ["italic"];};
    "constant.character.escape" = {fg = "#9AA6A1"; modifiers = ["bold"];};
    "constant.numeric" = {fg = "#939E99";};
    "constant.numeric.float" = {fg = "#939E99";};
    string = {fg = "#939E99"; modifiers = ["italic"];};
    "string.regexp" = {fg = "#939E99"; modifiers = ["italic"];};
    "string.special" = {fg = "#9AA6A1"; modifiers = ["bold"];};
    "string.special.symbol" = {fg = "#A7B3AE";};
    "string.special.url" = {fg = "#9AA6A1"; modifiers = ["bold"];};
    "string.special.path" = {fg = "#9AA6A1"; modifiers = ["bold"];};
    comment = {fg = "#536977"; modifiers = ["italic"];};
    "comment.block.documentation" = {fg = "#536977"; modifiers = ["italic"];};
    variable = {fg = "#A7B3AE";};
    "variable.builtin" = {fg = "#939E99"; modifiers = ["italic"];};
    "variable.parameter" = {fg = "#A7B3AE";};
    "variable.other.member" = {fg = "#A7B3AE";};
    "function" = {fg = "#C6D5CF";};
    "function.builtin" = {fg = "#9AA6A1"; modifiers = ["bold"];};
    "function.method" = {fg = "#C6D5CF";};
    "function.macro" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "function.special" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    keyword = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "keyword.control.conditional" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "keyword.control.repeat" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "keyword.control.import" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "keyword.control.return" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "keyword.control.exception" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "keyword.operator" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "keyword.function" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "keyword.storage" = {fg = "#6E99B2";};
    "keyword.storage.type" = {fg = "#6E99B2";};
    "keyword.storage.modifier" = {fg = "#6E99B2";};
    "keyword.directive" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    operator = {fg = "#C6D5CF"; modifiers = ["bold"];};
    punctuation = {fg = "#5B7E94";};
    "punctuation.delimiter" = {fg = "#5B7E94";};
    "punctuation.bracket" = {fg = "#5B7E94";};
    "punctuation.special" = {fg = "#5B7E94";};
    attribute = {fg = "#C6D5CF"; modifiers = ["bold"];};
    namespace = {fg = "#939E99"; modifiers = ["italic"];};
    label = {fg = "#C6D5CF"; modifiers = ["bold"];};
    tag = {fg = "#9AA6A1"; modifiers = ["bold"];};
    "tag.builtin" = {fg = "#9AA6A1"; modifiers = ["bold"];};
    special = {fg = "#9AA6A1"; modifiers = ["bold"];};
    "markup.heading" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "markup.heading.marker" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "markup.bold" = {modifiers = ["bold"];};
    "markup.italic" = {modifiers = ["italic"];};
    "markup.strikethrough" = {modifiers = ["crossed_out"];};
    "markup.link" = {fg = "#939E99"; modifiers = ["italic"];};
    "markup.link.url" = {fg = "#939E99"; modifiers = ["italic"];};
    "markup.link.text" = {fg = "#9AA6A1"; modifiers = ["bold"];};
    "markup.quote" = {fg = "#939E99";};
    "markup.raw.inline" = {fg = "#939E99"; modifiers = ["italic"];};
    "markup.raw.block" = {fg = "#939E99"; modifiers = ["italic"];};
    "markup.list.unnumbered" = {fg = "#9AA6A1"; modifiers = ["bold"];};
    "markup.list.numbered" = {fg = "#9AA6A1"; modifiers = ["bold"];};
    "diff.plus" = {bg = "#1C2C19";};
    "diff.minus" = {bg = "#3B2023";};
    "diff.delta" = {bg = "#1F2645";};
    warning = {fg = "#B77E64";};
    error = {fg = "#DE6E7C";};
    info = {fg = "#8190D4";};
    hint = {fg = "#B279A7";};
    "diagnostic.warning" = {underline = {color = "#B77E64"; style = "curl";};};
    "diagnostic.error" = {underline = {color = "#DE6E7C"; style = "curl";};};
    "diagnostic.info" = {underline = {color = "#8190D4"; style = "curl";};};
    "diagnostic.hint" = {underline = {color = "#B279A7"; style = "curl";};};
    "diagnostic.unnecessary" = {fg = "#B77E64";};
    "diagnostic.deprecated" = {fg = "#B77E64"; modifiers = ["crossed_out"];};
    "ui.background" = {fg = "#C6D5CF"; bg = "#0F191F";};
    "ui.text" = {fg = "#C6D5CF";};
    "ui.text.focus" = {fg = "#C6D5CF"; bg = "#1A2830";};
    "ui.text.inactive" = {fg = "#D1E0DA";};
    "ui.text.info" = {fg = "#C6D5CF";};
    "ui.cursor" = {fg = "#0F191F"; bg = "#63757C";};
    "ui.cursor.match" = {fg = "#C6D5CF"; bg = "#62415B";};
    "ui.cursor.primary" = {fg = "#0F191F"; bg = "#CEDDD7";};
    "ui.selection" = {bg = "#3A3E3D";};
    "ui.selection.primary" = {bg = "#3A3E3D";};
    "ui.statusline" = {fg = "#C6D5CF"; bg = "#20303A";};
    "ui.statusline.inactive" = {fg = "#D1E0DA"; bg = "#18252D";};
    "ui.statusline.normal" = {fg = "#0F191F"; bg = "#6E99B2"; modifiers = ["bold"];};
    "ui.statusline.insert" = {fg = "#0F191F"; bg = "#8190D4"; modifiers = ["bold"];};
    "ui.statusline.select" = {fg = "#0F191F"; bg = "#B279A7"; modifiers = ["bold"];};
    "ui.bufferline" = {fg = "#C6D5CF"; bg = "#20303A";};
    "ui.bufferline.active" = {fg = "#C6D5CF"; bg = "#0F191F"; modifiers = ["bold"];};
    "ui.bufferline.background" = {fg = "#D1E0DA"; bg = "#18252D";};
    "ui.popup" = {fg = "#C6D5CF"; bg = "#1D2C35";};
    "ui.popup.info" = {fg = "#C6D5CF"; bg = "#1D2C35";};
    "ui.menu" = {fg = "#C6D5CF"; bg = "#1D2C35";};
    "ui.menu.selected" = {fg = "#C6D5CF"; bg = "#3A5565"; modifiers = ["bold"];};
    "ui.menu.scroll" = {bg = "#405A6B";};
    "ui.linenr" = {fg = "#466273";};
    "ui.linenr.selected" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "ui.gutter" = {fg = "#466273"; bg = "#131F26";};
    "ui.gutter.selected" = {fg = "#C6D5CF"; modifiers = ["bold"];};
    "ui.cursorline.primary" = {bg = "#1A2830";};
    "ui.cursorline.secondary" = {bg = "#152128";};
    "ui.cursorcolumn.primary" = {bg = "#152128";};
    "ui.cursorcolumn.secondary" = {bg = "#152128";};
    "ui.window" = {fg = "#466273";};
    "ui.help" = {fg = "#C6D5CF"; bg = "#1D2C35";};
    "ui.highlight" = {fg = "#C6D5CF"; bg = "#62415B";};
    "ui.virtual.ruler" = {bg = "#53372B";};
    "ui.virtual.whitespace" = {fg = "#35444E";};
    "ui.virtual.indent-guide" = {fg = "#35444E";};
    "ui.virtual.inlay-hint" = {fg = "#4B6F84"; bg = "#152128";};
    "ui.virtual.wrap" = {fg = "#35444E";};
    "ui.virtual.jump-label" = {fg = "#0F191F"; bg = "#BE8CB3"; modifiers = ["bold"];};
  };

  kanagawabones = {
    "type" = {fg = "#9797A5";};
    "type.builtin" = {fg = "#9797A5";};
    "type.enum.variant" = {fg = "#BBB79E"; modifiers = ["bold"];};
    constructor = {fg = "#ADA992"; modifiers = ["bold"];};
    constant = {fg = "#A29E89"; modifiers = ["italic"];};
    "constant.builtin" = {fg = "#A29E89"; modifiers = ["italic"];};
    "constant.builtin.boolean" = {fg = "#DDD8BB"; modifiers = ["italic"];};
    "constant.character" = {fg = "#A29E89"; modifiers = ["italic"];};
    "constant.character.escape" = {fg = "#ADA992"; modifiers = ["bold"];};
    "constant.numeric" = {fg = "#A29E89";};
    "constant.numeric.float" = {fg = "#A29E89";};
    string = {fg = "#A29E89"; modifiers = ["italic"];};
    "string.regexp" = {fg = "#A29E89"; modifiers = ["italic"];};
    "string.special" = {fg = "#ADA992"; modifiers = ["bold"];};
    "string.special.symbol" = {fg = "#BBB79E";};
    "string.special.url" = {fg = "#ADA992"; modifiers = ["bold"];};
    "string.special.path" = {fg = "#ADA992"; modifiers = ["bold"];};
    comment = {fg = "#696977"; modifiers = ["italic"];};
    "comment.block.documentation" = {fg = "#696977"; modifiers = ["italic"];};
    variable = {fg = "#BBB79E";};
    "variable.builtin" = {fg = "#A29E89"; modifiers = ["italic"];};
    "variable.parameter" = {fg = "#BBB79E";};
    "variable.other.member" = {fg = "#BBB79E";};
    "function" = {fg = "#DDD8BB";};
    "function.builtin" = {fg = "#ADA992"; modifiers = ["bold"];};
    "function.method" = {fg = "#DDD8BB";};
    "function.macro" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "function.special" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    keyword = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "keyword.control.conditional" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "keyword.control.repeat" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "keyword.control.import" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "keyword.control.return" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "keyword.control.exception" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "keyword.operator" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "keyword.function" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "keyword.storage" = {fg = "#9797A5";};
    "keyword.storage.type" = {fg = "#9797A5";};
    "keyword.storage.modifier" = {fg = "#9797A5";};
    "keyword.directive" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    operator = {fg = "#DDD8BB"; modifiers = ["bold"];};
    punctuation = {fg = "#7D7D8D";};
    "punctuation.delimiter" = {fg = "#7D7D8D";};
    "punctuation.bracket" = {fg = "#7D7D8D";};
    "punctuation.special" = {fg = "#7D7D8D";};
    attribute = {fg = "#DDD8BB"; modifiers = ["bold"];};
    namespace = {fg = "#A29E89"; modifiers = ["italic"];};
    label = {fg = "#DDD8BB"; modifiers = ["bold"];};
    tag = {fg = "#ADA992"; modifiers = ["bold"];};
    "tag.builtin" = {fg = "#ADA992"; modifiers = ["bold"];};
    special = {fg = "#ADA992"; modifiers = ["bold"];};
    "markup.heading" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "markup.heading.marker" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "markup.bold" = {modifiers = ["bold"];};
    "markup.italic" = {modifiers = ["italic"];};
    "markup.strikethrough" = {modifiers = ["crossed_out"];};
    "markup.link" = {fg = "#A29E89"; modifiers = ["italic"];};
    "markup.link.url" = {fg = "#A29E89"; modifiers = ["italic"];};
    "markup.link.text" = {fg = "#ADA992"; modifiers = ["bold"];};
    "markup.quote" = {fg = "#A29E89";};
    "markup.raw.inline" = {fg = "#A29E89"; modifiers = ["italic"];};
    "markup.raw.block" = {fg = "#A29E89"; modifiers = ["italic"];};
    "markup.list.unnumbered" = {fg = "#ADA992"; modifiers = ["bold"];};
    "markup.list.numbered" = {fg = "#ADA992"; modifiers = ["bold"];};
    "diff.plus" = {bg = "#2A331F";};
    "diff.minus" = {bg = "#47272A";};
    "diff.delta" = {bg = "#22333A";};
    warning = {fg = "#E5C283";};
    error = {fg = "#E46A78";};
    info = {fg = "#7EB3C9";};
    hint = {fg = "#957FB8";};
    "diagnostic.warning" = {underline = {color = "#E5C283"; style = "curl";};};
    "diagnostic.error" = {underline = {color = "#E46A78"; style = "curl";};};
    "diagnostic.info" = {underline = {color = "#7EB3C9"; style = "curl";};};
    "diagnostic.hint" = {underline = {color = "#957FB8"; style = "curl";};};
    "diagnostic.unnecessary" = {fg = "#E5C283";};
    "diagnostic.deprecated" = {fg = "#E5C283"; modifiers = ["crossed_out"];};
    "ui.background" = {fg = "#DDD8BB"; bg = "#1F1F28";};
    "ui.text" = {fg = "#DDD8BB";};
    "ui.text.focus" = {fg = "#DDD8BB"; bg = "#2A2A37";};
    "ui.text.inactive" = {fg = "#E9E3C5";};
    "ui.text.info" = {fg = "#DDD8BB";};
    "ui.cursor" = {fg = "#1F1F28"; bg = "#7B7975";};
    "ui.cursor.match" = {fg = "#DDD8BB"; bg = "#614A82";};
    "ui.cursor.primary" = {fg = "#1F1F28"; bg = "#E6E0C2";};
    "ui.selection" = {bg = "#49473E";};
    "ui.selection.primary" = {bg = "#49473E";};
    "ui.statusline" = {fg = "#DDD8BB"; bg = "#363644";};
    "ui.statusline.inactive" = {fg = "#E9E3C5"; bg = "#292934";};
    "ui.statusline.normal" = {fg = "#1F1F28"; bg = "#98BB6C"; modifiers = ["bold"];};
    "ui.statusline.insert" = {fg = "#1F1F28"; bg = "#7EB3C9"; modifiers = ["bold"];};
    "ui.statusline.select" = {fg = "#1F1F28"; bg = "#957FB8"; modifiers = ["bold"];};
    "ui.bufferline" = {fg = "#DDD8BB"; bg = "#363644";};
    "ui.bufferline.active" = {fg = "#DDD8BB"; bg = "#1F1F28"; modifiers = ["bold"];};
    "ui.bufferline.background" = {fg = "#E9E3C5"; bg = "#292934";};
    "ui.popup" = {fg = "#DDD8BB"; bg = "#31313F";};
    "ui.popup.info" = {fg = "#DDD8BB"; bg = "#31313F";};
    "ui.menu" = {fg = "#DDD8BB"; bg = "#31313F";};
    "ui.menu.selected" = {fg = "#DDD8BB"; bg = "#54546D"; modifiers = ["bold"];};
    "ui.menu.scroll" = {bg = "#5D5D6F";};
    "ui.linenr" = {fg = "#646476";};
    "ui.linenr.selected" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "ui.gutter" = {fg = "#646476"; bg = "#232330";};
    "ui.gutter.selected" = {fg = "#DDD8BB"; modifiers = ["bold"];};
    "ui.cursorline.primary" = {bg = "#2A2A37";};
    "ui.cursorline.secondary" = {bg = "#272732";};
    "ui.cursorcolumn.primary" = {bg = "#272732";};
    "ui.cursorcolumn.secondary" = {bg = "#272732";};
    "ui.window" = {fg = "#646476";};
    "ui.help" = {fg = "#DDD8BB"; bg = "#31313F";};
    "ui.highlight" = {fg = "#DDD8BB"; bg = "#614A82";};
    "ui.virtual.ruler" = {bg = "#514531";};
    "ui.virtual.whitespace" = {fg = "#484856";};
    "ui.virtual.indent-guide" = {fg = "#484856";};
    "ui.virtual.inlay-hint" = {fg = "#6D6D8C"; bg = "#272732";};
    "ui.virtual.wrap" = {fg = "#484856";};
    "ui.virtual.jump-label" = {fg = "#1F1F28"; bg = "#AE9FCA"; modifiers = ["bold"];};
  };
}
