-- require("core.plugin_config.gruvbox")
-- require("core.plugin_config.nord")
require("core.plugin_config.catpuccin")
require("core.plugin_config.lualine")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.completions")
require("core.plugin_config.lsp")
require("core.plugin_config.dap")
-- require("core.plugin_config.nvim-tree")
