-- require("core.plugin_config.gruvbox")
-- require("core.plugin_config.nord")
if os.getenv("OPENAI_API_KEY") ~= nil then
  require("core.plugin_config.chatgpt")
end
require("core.plugin_config.catpuccin")
require("core.plugin_config.swenv")
require("core.plugin_config.fugitive")
require("core.plugin_config.neotree")
require("core.plugin_config.lualine")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.completions")
require("core.plugin_config.lsp")
require("core.plugin_config.dap")
require("core.plugin_config.undotree")
-- require("core.plugin_config.nvim-tree")
