source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "eraserhd/parinfer-rust" do %{
    cargo build --release
    cargo install --force --path .
}
plug 'Delapouite/kakoune-buffers'
plug "andreyorst/fzf.kak" defer "fzf" %{
    set-option global fzf_file_command 'rg --files --hidden --follow --glob "!.git/*"'
}

set-option global grepcmd 'rg+'
set-option global ui_options ncurses_status_on_top=false

colorscheme zenburn

define-command ide %{
    rename-client main
    set-option global jumpclient main

    new rename-client tools
    set-option global toolsclient tools
}

hook global WinDisplay .* info-buffers
map global user b ':enter-buffers-mode<ret>'              -docstring 'buffers…'
map global user B ':enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'
map global user f ':fzf-mode<ret>'                        -docstring 'fzf mode'
