source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "eraserhd/parinfer-rust" do %{
    cargo build --release
    cargo install --force --path .
}
plug 'Delapouite/kakoune-buffers'

set-option global grepcmd 'rg+'
set-option global ui_options ncurses_status_on_top=false

colorscheme zenburn

define-command ide %{
    rename-client main
    set-option global jumpclient main

    new rename-client tools
    set-option global toolsclient tools

    new rename-client docs
    set-option global docsclient docs
}

define-command -docstring 'Invoke fzf to open a file' -params 0 fzf-edit %{
    evaluate-commands %sh{
        if [ -z "${kak_client_env_TMUX}" ]; then
            printf 'fail "client was not started under tmux"\n'
        else
            file="$(rg --files --hidden --follow --glob ""!.git/*""|TMUX="${kak_client_env_TMUX}" fzf-tmux -d 15)"
            if [ -n "$file" ]; then
                printf 'edit "%s"\n' "$file"
            fi
        fi
    }
}

hook global WinDisplay .* info-buffers
map global user b ':enter-buffers-mode<ret>'              -docstring 'buffers…'
map global user B ':enter-user-mode -lock buffers<ret>'   -docstring 'buffers (lock)…'
map global user f ':fzf-edit<ret>'                        -docstring 'files find'
