#!/bin/sh

VARIABLE_PITCH_FONT='/mnt/font/PragmataPro/15a/font'
FIXED_PITCH_FONT='/mnt/font/PragmataPro/15a/font'

export TERM=dump
export PAGER=nobs
export MANPAGER=nobs
export EDITOR=E2
export TERM=dumb
export MANPAGER=nobs
export PAGER=nobs

export PLUMBFILE=$HOME/bin/plumbing
export PLAN9=$HOME/plan9port
export SHELL=$PLAN9/bin/rc
export PATH=$PLAN9/bin:$PATH
export MANPATH=$MANPATH:$PLAN9/man

if [ "$(pgrep plumber)" ]; then
    echo "Plumber is running"
else
    echo "Starting plumber"
    9 plumber
fi

if [ "$(pgrep fontsrv)" ]; then
    echo "Fontsrv is running"
else
    echo "Starting fontsrv"
    9 fontsrv &
fi

cat $PLUMBFILE $PLAN9/plumb/initial.plumbing | 9 9p write plumb/rules

acme -l acme.dump -a -f "$VARIABLE_PITCH_FONT" -F "$FIXED_PITCH_FONT" &
