#!/usr/bin/env sh

VARIABLE_PITCH_FONT='/mnt/font/PragmataPro/16a/font'
FIXED_PITCH_FONT='/mnt/font/PragmataPro/16a/font'

export PAGER=nobs
export MANPAGER=nobs
export EDITOR=E2
export TERM=dumb
export MANPAGER=nobs
export PAGER=nobs

export PLUMBFILE=$HOME/lib/plumbing
export SHELL=/usr/local/plan9/bin/rc
export PLAN9=/usr/local/plan9
export PATH=$PATH:$PLAN9/bin
export MANPATH=$MANPATH:$PLAN9/man

export NAMESPACE=`mktemp -d -t plan9`
export PLAN9_MPOINT=/tmp/`basename $NAMESPACE`

export ACME_MPOINT=`echo $PLAN9_MPOINT`_acme

mkdir -p $ACME_MPOINT

9 plumber;

9 cat $PLUMBFILE $PLAN9/plumb/initial.plumbing | 9 9p write plumb/rules

9 acme -a -m $ACME_MPOINT -f "$VARIABLE_PITCH_FONT" -F "$FIXED_PITCH_FONT" &
