#!/usr/bin/env sh

# 9 unmount /mnt/plumb
# 9 unmount /mnt/acme
# 9 unmount /mnt/fontsrv
if pgrep -x "plumber" > /dev/null
then
    pkill plumber
fi

if pgrep -x "acme" > /dev/null
then
    pkill acme
fi

if pgrep -x "fontsrv" > /dev/null
then
    pkill fontsrv
fi

echo "unmount acme"
if mount | grep plan9 | grep acme > /dev/null
then
    umount `mount | grep plan9 | grep acme | awk '{print $1}'`
fi

echo "unmount fontsrv"
if mount | grep plan9 | grep font > /dev/null
then
    umount `mount | grep plan9 | grep font | awk '{print $1}'`
fi

echo "unmount plumb"
if mount | grep plan9 | grep plumb > /dev/null
then
    umount `mount | grep plan9 | grep plumb | awk '{print $1}'`
fi

echo "delete namespace"
rm -rf `9 namespace`
