#!/usr/bin/env bash

if [ ! "$(which fzf)" ]; then
	echo '+----------------------------------------------------+'
	echo '| The fzf is not found. Go get it tiger!             |'
	echo '|                                                    |'
	echo '+----------------------------------------------------+'
	exit 1
fi

fzf -f "$1"

if [ $? -ne 0 ]; then
	echo 'Not found'
fi
