#!/usr/bin/env bash

if [ ! "$(which fzy)" ]; then
	echo '+----------------------------------------------------+'
	echo '| The fzy is not found. Go get it tiger!             |'
	echo '|                                                    |'
	echo '+----------------------------------------------------+'
	exit 1
fi
if [ ! "$(which rg)" ]; then
	echo '+----------------------------------------------------+'
	echo '| The rg is not found. Go get it tiger!              |'
	echo '|                                                    |'
	echo '+----------------------------------------------------+'
	exit 1
fi

rg --files --hidden --glob "!.git/*" | fzf -f "$@"

if [ $? -ne 0 ]; then
	echo 'Not found'
	echo $?
fi
