#!/usr/bin/env bash

tmuxgetir () {
    SELECTED_PROJECT=$(ls -1 $ZEK_DEVEL_HOME/${1:-getir}/ |
        tail -n +1 |
        fzf --exit-0 --prompt="Project: ") || return $?

    tmuxinator g "$SELECTED_PROJECT" "${1:-getir}"
}

tmuxgetir "$@"
