#!/usr/bin/env bash

if [ ! "$(which rg)" ]; then
	echo '+----------------------------------------------------+'
	echo '| The ripgrep is not found. Go get it tiger!         |'
	echo '|                                                    |'
	echo '+----------------------------------------------------+'
	exit 1
fi

rg --smart-case --color never --no-heading -n "$@"

if [ $? -ne 0 ]; then
	echo 'Not found'
fi
