# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="normz"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how many often would you like to wait before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git brew git-extras osx pip sublime vagrant tmux tmuxinator node npm web-search docker zsh-syntax-highlighting lein)

source $ZSH/oh-my-zsh.sh
# Customize to your needs...
export PATH=/Users/zekus/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin

fpath=($HOME/.zsh/func $fpath)
typeset -U fpath

export WORKON_HOME=$HOME/.virtualenvs
export VIRTUAL_ENV_DISABLE_PROMPT=true
#export PROJECT_HOME=$HOME/devel/projects
source /usr/local/bin/virtualenvwrapper.sh
export PATH=/usr/local/bin:/usr/local/opt/ruby/bin:$PATH

alias vi=/usr/local/bin/vim
alias vim=/usr/local/bin/vim

alias ruby=/usr/local/bin/ruby

export EDITOR=/usr/local/bin/vim
export DEFAULT_USER=zekus
export LC_ALL=en_US.UTF-8
export PATH=/usr/local/share/npm/bin:$PATH

unsetopt correct_all

alias mux=tmuxinator

bindkey -M viins 'jj' vi-cmd-mode
bindkey '^r' history-incremental-search-backward
bindkey '^p' up-line-or-history
bindkey '^n' down-line-or-history
autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line
#
export GOPATH=$HOME/go
export PATH=$PATH:$GOPATH/bin
