if [ -f ~/.bashrc ]; then
	source ~/.bashrc
fi

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/Users/zekus/.sdkman"
[[ -s "/Users/zekus/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/zekus/.sdkman/bin/sdkman-init.sh"
