export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/go

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/opt/go/libexec/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$GOPATH/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.ghcup/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH="/usr/local/opt/icu4c/bin":$PATH
export PATH="/usr/local/opt/icu4c/sbin":$PATH

export EDITOR=nvim
export MANPAGER="nvim -c 'set ft=man' -"
export PGDATA=/usr/local/var/postgres

export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
export FZF_ALT_C_COMMAND='bfs -type d -nohidden'

export HOMEBREW_NO_INSTALL_CLEANUP=1

alias mux="tmuxinator"

eval "$(rbenv init -)"
eval "$(nodenv init -)"
eval "$(jenv init -)"

[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

if [ "${BASH_VERSINFO[0]}" -gt 4 ] || ([ "${BASH_VERSINFO[0]}" -eq 4 ] && [ "${BASH_VERSINFO[1]}" -ge 1 ]) then
	source <("/usr/local/bin/starship" init bash --print-full-init)
else
	source /dev/stdin <<<"$("/usr/local/bin/starship" init bash --print-full-init)"
fi
