export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/go

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/opt/go/libexec/bin:$PATH
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$GOPATH/bin:$PATH
export PATH=$HOME/.local/bin:$PATH
export PATH=$HOME/.cabal/bin:$PATH
export PATH=$HOME/bin:$PATH
export PATH="/usr/local/opt/icu4c/bin":$PATH
export PATH="/usr/local/opt/icu4c/sbin":$PATH

export EDITOR=nvim
export MANPAGER="nvim -c 'set ft=man' -"
export PGDATA=/usr/local/var/postgres

export RUST_SRC_PATH=$(rustc --print sysroot)/lib/rustlib/src/rust/src

export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*"'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND
export FZF_ALT_C_COMMAND='bfs -type d -nohidden'

export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

export HOMEBREW_NO_INSTALL_CLEANUP=1
export BASH_COMPLETION_COMPAT_DIR="/usr/local/etc/bash_completion.d"

alias mux="tmuxinator"

eval "$(rbenv init -)"
eval "$(nodenv init -)"
eval "$(jenv init -)"

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"
if [ -e /Users/zekus/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/zekus/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

if [ "${BASH_VERSINFO[0]}" -gt 4 ] || ([ "${BASH_VERSINFO[0]}" -eq 4 ] && [ "${BASH_VERSINFO[1]}" -ge 1 ]) then
	source <("/usr/local/bin/starship" init bash --print-full-init)
else
	source /dev/stdin <<<"$("/usr/local/bin/starship" init bash --print-full-init)"
fi

export SDKMAN_DIR="/Users/zekus/.sdkman"
[[ -s "/Users/zekus/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/zekus/.sdkman/bin/sdkman-init.sh"
