#!/bin/sh
set -o errexit -o nounset

PATH="/usr/local/bin:$PATH"

main() (
    root_dir="$(git rev-parse --show-toplevel)"
    git_dir="$(git rev-parse --git-dir)"

    cd "$root_dir"
    trap 'rm -f GPATH GRTAGS GTAGS gtags.files' EXIT
    git grep --cached --files-with-matches "" > gtags.files
    gtags --gtagslabel=pygments
    rm gtags.files
    mv GPATH GRTAGS GTAGS "$git_dir/"

    echo "gtags index created at $git_dir/GTAGS"
)

main
